name: Deploy PHP to GCP VM

on:
  push:
    branches:
      - main  # Triggers the workflow only on push to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner environment

    steps:
    - name: Checkout Code from Repository
      uses: actions/checkout@v3

    - name: Set up SSH Key and Known Hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy PHP file to GCP VM
      run: |
        scp -o StrictHostKeyChecking=no ./getdatavariable.php ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_PATH }}

