name: Deploy PHP to GCP VM

on:
  push:
    branches:
      - main  # Triggers the workflow only on push to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner environment

    steps:
    - name: Checkout Code from Repository
      uses: actions/checkout@v3
      

        
    - name: Deploy PHP file to GCP VM
      run: |
        sshpass -p 'iplon321' scp -o StrictHostKeyChecking=no ./getdatavariable.php root@34.100.176.104:/home/kesava/getdatavariable/getdatavariable.php


    - name: Restart Docker container
      run: |
        sshpass -p 'iplon321' scp -o StrictHostKeyChecking=no root@34.100.176.104 \
        "docker restart apache"
        
        


